apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog.fullname" . }}-config
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.global.environment | quote }}
  PORT: {{ .Values.service.port | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
