apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sa-platform.fullname" . }}-cron1
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: cron1
data:
  DB_HOST: {{ printf "%s-mysql" .Release.Name | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sa-platform.fullname" . }}-cron2
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: cron2
data:
  DB_HOST: {{ printf "%s-mysql" .Release.Name | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
