---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: AgAhYnhLkRS57BNyoD3uhhYtX03IUh6jXfxuWc8LLdVEI55aEWA1Qp80dD8XhFOohxL3q1bDmnmadUPlhYvdu/uFNyeA0WQsGeNafKQJE6xyNrSdCVmVtgNRKTEF4a8tWz6AbkTWBiRFYxiLAvklPohev+ojAJSZnMSqE6ARSjFZHOc5aJW8UStR2Mg2GoSi9UK5/ZEF8+JvCfpTCvOt8t3vER2z8TMRT0YPFpAG1ka5r6CzXeoPnv2Jr0Nvbk85eYznrhYfdQPEDgYv4W7JKlo07sPtBdFImWQvQgFvAFBi7Xrh3CK3vIElxw8eSabgxyTxbzJkOwFFejJNbgRv2qH2okMzHqr51zlG1swDWR0Baik7qAh5AU8F7d/Rvwp5+eu+/OpL40LE+O2/HLfuLOzhO7xLxNc4HjI09s/OcFeI1YLhKnh5a12I/7RW+iYIEgYQKGTe6qJmtfHdGoOnseB8f8Hwjwt1SybX2WlYcgPbN4Jl0bTBFq07yrhGf9pIOGhnmuw9PeDjy7YraDGKL4k8Bug4RcxGJstC55eXJ2lIJRY8upYCPvbfFDAirqA6OXA4BOAXzyXvflHbsve4Zp3wRAfKq6XArif/MpheJzXKA+oKc7oofFIp/YNbZMR/X7NHrF0tKwsfbM+U3o03zxPHpqQEFrOxu7+NlKKovv5cq8NDuU7xmq1jrwhpQGoSrV6a69EQpiRaISS38hLIrJTKqa/tzFUPUH1AoGZmFIVzKfpE1svRb+tvHNMGBqxChQID6AaxejK0UJbjJo5fqbx0slFb8gXX/LDm+vSvx76fH+6hlPUZ2HJFWL3CqFqu/B7EbQ2XAXKtzYsaTBId5psP6qPhi+vD9+oHc4LUEYKHq92f3e9T7JYFBjxtcVxVuCKW5I8I7tOCDjObxWwbHdxrwujl9CDrQ78arvHe
  template:
    metadata:
      name: ghcr-secret
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
