---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: AgAoRKqOkZ8v2iujU8p8hD2l7N56nxJVv9eEgruQoZ8glf13xpHDsgouxNHxtdDQVu87+0/5H0kwKnAK3MTEj1IvYwjOh6+VsNSiWq1QCvBuC18Sfmi0ETxuOn63ywI2RxBfn1+9GSjYSq9zAxkKz4X8Q4nx8H460JOyL+yjC/7j0J2BE0GdpqEbAevP37aKtj8xQCsPUEcZ7WJd/A6/EDOCaTENDEibCnHxJF0O89DDN+TybTPbOI6KpgV/bsa1hO2PX+Eu0OnrIBzIUAC07tc3OqYXu/2dAAt0AjA9A/5awHr6t8ouL/Nvo01Q72xpSXjaI2k2MDh3ylkd1U6Uwt82f4cJRLFHQprOxVWrXpg32aiD7VZZDZEnep2EZpqAD8+LKIlBgZgGDR4LSA0rqqmXJwo557LdlkcZoUZxZwPhwhWrzBmJ3jDYI8+81MAAXqicVybY5RVMwux6OnHtInl7NSpnwmU0vzhhamOW7zCwcVHudMcSLBw165YLr5CzdKzyLPL2IGk5G16v1ib7LlBu1fauSbnLiC/ZSZTBLlHJUiR/y68VjQEdpPRtF2LIrAG0Rv+0a/D8IJCLKLVoVG9hnolJHQBePOFnNX5FWmiJUJrkXCeyc9ScA+/kCW4rcaveZlmOpKhRHvYLg5IxpIPOeKoThc2XEMocMPtGvRgHUUWOw6HuknTSwYRf7b9BuOAqO21UwsdywKNtqGH07jv2ic74aceW9gRwp4kw27qB2fAGYfw3CiUybMlJJZ3ZZEITOs38MDhF6u2F2Ml7JT462gQywW1/W8z/2kgJ9CqROi7CrMkp3w3QYioN+6ZgdIWAEtxY6RNo9rSxwcsALTlt9AIXusrMwLrO2JZD2OfwpA1chyoSRdznhhhZhdKI5zxBkqTziNF7akids3fg4h2PoWeexZTYLUDQjXJm
  template:
    metadata:
      name: ghcr-secret
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
