---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: sa-p5
spec:
  encryptedData:
    .dockerconfigjson: AgCPrJXuHKV8hXkeaYEkSTXHbL4dLhjFD8FkahmcViLFs18KLeXPu+yS5LureEoaOywO3J+BJCsLt55XNIAeJQovS11fuvA295CJ8ddF98d3W5zhFBiQz5S24QtmQxQXVLTaJ2XWA0AIM4ZnYbn+p0PP+6uGCsqdMlvR+ktJ59k88A/a1h5bNs8P4w+1ouJ3T7naB/HVB2iiLUBwkWFx/3ipiFP0nizvf7whAUhZ2IVlQBsEBEAHXcUn/F1ibzGmr78VsxpicX1wQx1h3FnLBURtDPPGhnYxLy7na7EI+zM6e9VCoKOpi2K7S3LbzjnKcmOOhUukktQpG9jFAj79YcmPp+0N9rqpXbgRVy3WYPi32bVDsdls0gFOGPaU/z49P8QrS6cSnGIg+AqrANTJ5J3bUOnpxFuGPTVok1CHcxNULWRYb/YELZoarQtIUtWrths7et6rDtjiQ533m1ftdPWtFKfzI1G9eZHU3GVCts6b/N8BaYKfcn3QW4qpZy5Ak5JF8OY509RZ67DrmUxS1fusa/guS9SZEIRF6q1gxOxqWc+eK2vowUw78GMXf9rbG9FGSdsasJFWJId1/zoMksk8d8zeCtslQntQZIk/ff7e8CM355vLDbHroj9xGqWtLVn49F8v32N993p81OHZR69YVogoPPev0AJ5nqxueGv2t+jzie1DmUx7HlKn/RHZF82yLC6A9woJ+K2GwJ1W7jJq3g0EhvDRCNr2AJoH9Zg+yww/WLtKzeoW6zhE+tS0xvgVuwsGT9wES7hUE0HAp5NXBBR2eL/VnhFvMQS0ajw9uu5NqHgnXOBApUGovXG+08jjjb9KX4zNO+g0Ibk0XrOO0pldnhVBGs30gUvnZkpjOvkGuuzdNIoyOi3tNsphcQT2PZJv0vVnhrMtpjlivLG5K7vYhneWvC5IZ9zD
  template:
    metadata:
      name: ghcr-secret
      namespace: sa-p5
    type: kubernetes.io/dockerconfigjson
