---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: sa-p5
spec:
  encryptedData:
    .dockerconfigjson: AgCyLZXrUR1RwP89YXGMyIXW/OyiJ8Bbju03QZB8orgcwgPLVel+AGSk5gKWdGKWDZBdIWf9kc66CVBsFRq3osMRwNOm3rValgMSmiX4MS0vL1GzuiHTOKI3+rMqXbYw8Fe4xx/YsEG7fOvJHE+0lU4btGmfy3ahk37iQX725UBBELJPpQ5qnRLHbdftJ4Q2sZIV6B3Pf5IQIfP1zTDm0yIFjf0RP+hX96b+Kx/uYf87SEic3HUNDHuEs2DZpRqhSGOX9AOtkQIEjxgR5O976f8wfeMEds8PcQdD9O8WPArx6Eua7WMEYnacB0aFLapXxZhen5+btrKbI7kzeSfHNPd62zantAv49qNPOgTRJOcnWcDk4yl6ovI0xwE+eSGXe9IGifKRMb/qkOenVLRL7zYs0RLkfjZiJiVyltPTlvmT1Q1k+nN6UFuK29ynQ44mKOvRxV7ialiDqQG+rDqCae0QJNCOPDX80FwJL1Bt+VFhck9SxqBT1wG3RVvf5Gi6SWJwT9BVeSbinuvyzNwhaeUiRSYo0qyaMVRluf+TRuPDvb11+bXbaNE3hetZ5bNetGI07mWA0bWqiWdHFxicc06EsfjVBiAlXojVqwOmH86MTZPK/LJOxdl3EV6+OupZOtcNbOh0QSt8O7P1n7QlyI1Bgkh3RLEGJfSvtymwiE5RHKjaGDhh+kKGOtxHyJExi341Susl5DjGbAYiWLKwIwP9veoGVUK89w52oDKtnak7VUd2BrOYt8RVI/6UFgQOIhVAIaWxljlPTl+h4N/6UkpaQQvT/nPbRcLQ2yZuFiw5dou34iR8RrYNlIbBNNWeVrJtANTC+4agJ/p7H2XQ5kAdAYqn4cxj1FRsP2hB32ZQqIsSIUKeF7LrlZyUgl8KvGIoBFLFFm1s2NKeSyoOo0PjIKJsbo8O0iS0RaD0
  template:
    metadata:
      name: ghcr-secret
      namespace: sa-p5
    type: kubernetes.io/dockerconfigjson
