---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-nats-auth
  namespace: sa-p5
spec:
  encryptedData:
    NATS_URL: AgAkDb3jQCYfueWv3mffET6ljayVRLNXz/f5JQVXSQmfMRr0P1GAhepnYi1+fn1ZYVFLgul1r4ugXHyYH/Gn0mVl7Y7/BW0hB9hHjRKkXF8ULtlBvQiPL0w1ax3zx09Ejbyz8poogk6DcgnC1TB5xSG6yE8sjuYOAojf3ttwK/B2U6peGearr2d+7h0OzcTt11uduOX132nIx7BXv7e9E7KafEiMTdcaxcxoHZGdDIxFHUcZs+tarRAe9JKmY1hLssxxauWwaRJ4fyMBu7X3c+duMB5HxEi3Bos3vrEpfdFiqH8hefQle6FW/hDvIRuBhnQww9OacUc0D4dM8/pBIGj591nD9QdIm14NYO1erhqOmiZJfi0RVTit9VYXLMHLPPPpcV8oQCpuiYAyQNuvaR2mGnkgf3gGMvEk50u00/aEpE1aFCfChV6u4BVRT4ATqPcfdsa9AsyZD/SbbTDjS360P0mlziijsltY50zMsnB5NplHJnWfeMgqrjBe8wtANQiPANNe23nX67JzFvR0N2adjuPD4yDB8ouDft4j1/CN7e34K7AGUwex3rUQfaJNusFcE9lRmlCUf32K9cDck/Cv6gDiia6cZJrV7xLryd9b2dZ2G02QOhA8Z2/vchU3Ta21A38+TupVJ/VP81/lbxPa7zTEBNNQn2EiNSTXpbGQAEwmMo1saGVDCN+zYX0OgfqucYXCD2/UAVQVdzyTbDN5QhjW4PhhVeQ39ulCO6mdMkWa2WGcBY/H8Ljj+rTT3VVNaQyCiBPwet5XiAL5jL85ZkDY+IM=
    token: AgClEz3x8/J+dzCZDOHczScsN5zXtWoM0rbyn2HZ/shVPasV9UzSb7yR7upow9EBiqfxFcLpFF4bj4WTkiCGLwE82uBJJ/SrygS+4R7Bl5e48ElwVSDsmP7gieoZTYXXhkoRpnsS/2VJZz0DFWucyDZtOf0TbZyDiNcRpss56z7esU7F/iYfSKr174XfyrqoJTcaUo8r0pMqMINFSUsioUwqOlYutyYJGr7pS2YiIjEnKxqx4fjs6pbjxBrvrEt3abuTelu04rDdmODqT1deUaXqy8/kvjOqu69OJYyr24iH0sd3lzT2vXmHuMHkpl1ol6Qfvyr5C/ojJlsPGx0kufjFOPMjWxU+rt4qIn3XsqoJGK5IUtRhrV1OTBntiJmeOcQG3lOclExxlJ0sCyX8W4BtW2I+r19FIn8BsDBAIkPFVUZt0VSmuv/OlK/rxk7Z5ZUZsrw+5z6TqoLZg7NDozVPB9kPayKoPEtbCSGQvdO9pVIAwj5kyz4w59fElNmiALVu8Co6nVDS3vmzbCbjpuaJPQJx11T12UNg3dhJ6y8T8PPXP65NQAZ/cmF8MduRqBm6lfq/PKPdMIm8+HG1zjo4qAQtUUo2UdBrTsxfPYTIs2JReDgtcNHUrut1emwcfkvksclR/k9nfKqTuuJAULffIToLR70bo8vcZoXDbRIWmz6pC2rvVqb4pAYtOEvifPkMbfo0dNGYEbQdc2+Me2PT4pjdUI97+51YIJUQ+SozZBRGaTPkd9nN
  template:
    metadata:
      name: sa-platform-nats-auth
      namespace: sa-p5
    type: Opaque
