apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
---
# Argo Rollouts añade a este selector el hash de la revisión estable.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}-stable
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
---
# El AnalysisTemplate usa este Service para consultar solo la revisión candidata.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}-canary
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
