image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

auth:
  username: root
  database: catalog_db
  existingSecret: ""

persistence:
  enabled: true
  size: 2Gi

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

global:
  storageClass: standard
