apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.fullname" . }}-config
  labels:
    {{- include "orders.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.global.environment | quote }}
  PORT: {{ .Values.service.port | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
  DB_HOST: {{ printf "%s-mysql" .Release.Name | quote }}
  DB_PORT: "3306"
  DB_USER: {{ .Values.config.databaseUser | quote }}
  DB_NAME: {{ .Values.config.databaseName | quote }}
  CATALOG_SERVICE_URL: {{ printf "http://%s-catalog:8000/graphql" .Release.Name | quote }}
