apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-mysql"
  labels:
    app: mysql
spec:
  serviceName: "{{ .Release.Name }}-mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 999
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.secretName" . | quote }}
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.secretName" . | quote }}
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.secretName" . | quote }}
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.secretName" . | quote }}
                  key: DB_NAME
          ports:
            - containerPort: 3306
              name: mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 3306
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/
            {{- if .Values.persistence.enabled }}
            - name: mysql-data
              mountPath: /var/lib/mysql
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: init-scripts
          configMap:
            name: "{{ .Release.Name }}-mysql-init"
        {{- if .Values.persistence.enabled }}
        - name: mysql-data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-mysql-data"
        {{- end }}
