apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notifications.serviceAccountName" . }}
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "notifications.fullname" . }}-role
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "notifications.fullname" . }}-rolebinding
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "notifications.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "notifications.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
